In [ ]:
!pip install google-api-python-client
!pip install isodate

Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (2.188.0)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.31.1)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.43.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (0.3.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (2.29.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client) (4.2.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.72.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (1.27.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.32.4)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (6.2.4)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (4.9.1)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client) (3.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0,>=1.32.0->google-api-python-client) (0.6.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client) (2026.1.4)
Collecting isodate
  Downloading isodate-0.7.2-py3-none-any.whl.metadata (11 kB)
Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Installing collected packages: isodate
Successfully installed isodate-0.7.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Imports
from googleapiclient.discovery import build
import pandas as pd
import time
from datetime import datetime, timedelta
import datetime, timedelta, timezone
import isodate

In [ ]:
# Set up
API_KEY = '##########################'
youtube = build("youtube", "v3", developerKey=API_KEY)

# Channels ID
channels = {
    "BBC News": "UC16niRr50-MSBwiO3YDb3RA",
    "CNN": "UCupvZG-5ko_eiXAupbDfxWw",
    "The Young Turks": 'UC1yBKRuGpC1tSM73A0ZjYjQ',
    "The Jimmy Dore Show": "UC3M7l8ved_rYQ45AVzS0RGA"
}

In [ ]:
# Functions for: getting list of channels uploads; fetching videos (no shorts; no lives)

def get_uploads_playlist_id(channel_id, youtube):
    request = youtube.channels().list(
        part="contentDetails",
        id=channel_id
    )
    response = request.execute()
    return response["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]


def get_filtered_videos_from_channel(
    channel_id,
    youtube,
    months_back=3,
    min_minutes=2
):
    videos = []
    next_page_token = None

    cutoff_dt = datetime.now(timezone.utc) - timedelta(days=months_back * 30)
    uploads_playlist_id = get_uploads_playlist_id(channel_id, youtube)

    while True:
        request = youtube.playlistItems().list(
            part="snippet",
            playlistId=uploads_playlist_id,
            maxResults=50,
            pageToken=next_page_token
        )
        response = request.execute()

        video_ids = []
        video_snippets = {}

        for item in response.get("items", []):
            published_at = datetime.fromisoformat(
                item["snippet"]["publishedAt"].replace("Z", "+00:00")
            )

            # limit for cutoff date
            if published_at < cutoff_dt:
                return pd.DataFrame(videos)

            vid = item["snippet"]["resourceId"]["videoId"]
            video_ids.append(vid)
            video_snippets[vid] = {
                "video_id": vid,
                "title": item["snippet"]["title"],
                "description": item["snippet"]["description"],
                "published_at": published_at,
                "channel_id": channel_id
            }

        # fetching info on duration and live status
        details_request = youtube.videos().list(
            part="contentDetails,snippet",
            id=",".join(video_ids)
        )
        details_response = details_request.execute()

        for video in details_response.get("items", []):
            vid = video["id"]

            duration = isodate.parse_duration(
                video["contentDetails"]["duration"]
            ).total_seconds() / 60

            live_status = video["snippet"]["liveBroadcastContent"]
            title = video_snippets[vid]["title"].lower()

            if (
                duration >= min_minutes
                and live_status == "none"
                and "#shorts" not in title
            ):
                videos.append(video_snippets[vid])

        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break
        time.sleep(0.3)

    return pd.DataFrame(videos)

In [ ]:
# Using functions to fetch videos: loop on chosen channels
all_videos = pd.DataFrame()
for name, cid in channels.items():
    print(f"\nFetching videos from {name}")

    df = get_filtered_videos_from_channel(cid, youtube)
    df["channel"] = name
    all_videos = pd.concat([all_videos, df], ignore_index=True)

print(f"\nTotal videos collected: {len(all_videos)}")

all_videos.to_csv("/content/drive/MyDrive/ANNO2/PRIMO PERIODO 2/SOCIAL MEDIA/PROJECT/videos.csv", index=False)

Fetching videos from BBC News...

Fetching videos from CNN...

Fetching videos from The Young Turks...

Fetching videos from The Jimmy Dore Show...

Total videos collected: 2645

In [ ]:
# Videos' distribution per channel
print(all_videos['channel'].value_counts())

channel
CNN                    1054
BBC News                625
The Young Turks         590
The Jimmy Dore Show     376
Name: count, dtype: int64

In [ ]:
# Information retrieved
all_videos.columns

Index(['video_id', 'title', 'description', 'published_at', 'channel_id',
       'channel'],
      dtype='object')

In [ ]:
# Total fetched videos per month (check on temporal distribution and constraint on cutoff date)
print(pd.to_datetime(all_videos['published_at']).dt.to_period('M').value_counts().sort_index())

# Min and max date per channel
print(all_videos.groupby('channel')['published_at'].agg(['min', 'max', 'count']))

published_at
2025-10    155
2025-11    961
2025-12    919
2026-01    610
Freq: M, Name: count, dtype: int64
                                          min                       max  count
channel
BBC News            2025-10-29 13:56:44+00:00 2026-01-22 19:30:08+00:00    625
CNN                 2025-10-25 21:31:50+00:00 2026-01-22 19:31:22+00:00   1054
The Jimmy Dore Show 2025-10-29 18:00:30+00:00 2026-01-22 20:05:17+00:00    376
The Young Turks     2025-10-30 00:30:06+00:00 2026-01-22 06:45:00+00:00    590

/tmp/ipython-input-1565064824.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  print(pd.to_datetime(all_videos['published_at']).dt.to_period('M').value_counts().sort_index())

In [ ]:
# Snippet of df
all_videos

,video_id,title,description,published_at,channel_id,channel
0,JiUoqt4cMrU,Ukraine President Zelensky criticises Europe f...,"In a speech to world leaders, Ukraine Presiden...",2026-01-22 19:30:08+00:00,UC16niRr50-MSBwiO3YDb3RA,BBC News
1,LgPQtGMUXAc,Is Canada leading the global resistance agains...,Canadian Prime Minister Mark Carney seemed to ...,2026-01-22 17:30:07+00:00,UC16niRr50-MSBwiO3YDb3RA,BBC News
2,bALbBkpC3bc,Donald Trump launches 'Board of Peace' with wo...,US President Donald Trump said his 'Board of P...,2026-01-22 15:32:01+00:00,UC16niRr50-MSBwiO3YDb3RA,BBC News
3,H-ZzXK0ObNw,UK holds off joining Trump's Board of Peace ov...,UK Foreign Secretary Yvette Cooper has said th...,2026-01-22 11:59:26+00:00,UC16niRr50-MSBwiO3YDb3RA,BBC News
4,BY11cl7ZrC0,Donald Trump backtracks on using force over Gr...,Donald Trump has backed down over Greenland - ...,2026-01-21 23:02:37+00:00,UC16niRr50-MSBwiO3YDb3RA,BBC News
...,...,...,...,...,...,...
2640,fdvbWUQ1Zxk,TPUSA Execs GASLIGHT About Mikey McCoy’s Bizar...,"Recently, those questioning the dominant narra...",2025-10-30 17:56:55+00:00,UC3M7l8ved_rYQ45AVzS0RGA,The Jimmy Dore Show
2641,gyTF9A6Y-h4,Kash Patel SHUTS DOWN Charlie Kirk Investigati...,FBI Director Kash Patel and the Trump administ...,2025-10-30 16:39:33+00:00,UC3M7l8ved_rYQ45AVzS0RGA,The Jimmy Dore Show
2642,R8tyImlJumk,New Jimmy Dore Hip Hop Track Is Fire!,A new AI-generated rap song about Jimmy Dore’s...,2025-10-30 01:01:48+00:00,UC3M7l8ved_rYQ45AVzS0RGA,The Jimmy Dore Show
2643,czgU8RC7WBg,“Anti-Violence” Actor Michael Rapaport Attacks...,During a recent anti-Mamdani rally in New York...,2025-10-29 18:46:17+00:00,UC3M7l8ved_rYQ45AVzS0RGA,The Jimmy Dore Show
2644,h2iP8YdXfds,Meet The AIPAC-Funded GOP Candidate Vying To B...,President Donald Trump and AIPAC are backing c...,2025-10-29 18:00:30+00:00,UC3M7l8ved_rYQ45AVzS0RGA,The Jimmy Dore Show

In [ ]:
# Fetch comments for each video (the max is needed to avoid execution errors)
def get_video_comments(video_id, max_comments=200):
    comments = []
    try:
        request = youtube.commentThreads().list(
    part="snippet",
            videoId=video_id,
            maxResults=100,
            textFormat="plainText"
        )
        while request and len(comments) < max_comments:
            response = request.execute()
            for item in response.get("items", []):
                snippet = item["snippet"]["topLevelComment"]["snippet"]
                comments.append({
                    "video_id": video_id,
                    "comment_id": item["id"],
                    "author": snippet["authorDisplayName"],
                    "comment": snippet["textDisplay"],
                    "likes": snippet["likeCount"],
                    "published_at": pd.to_datetime(snippet["publishedAt"], utc=True)
                })
            request = youtube.commentThreads().list_next(request, response)
            time.sleep(0.2)
    except Exception as e:
        print(f"Error fetching comments for video {video_id}: {e}")
    return pd.DataFrame(comments)

In [ ]:
# Using function to fetch comments on previously obtained videos
comments_all = pd.DataFrame()
for vid in all_videos["video_id"].unique():
    print(f"Fetching comments for video: {vid}")
    df = get_video_comments(vid)
    # Assign the channel name to the comments DataFrame
    channel_name = all_videos[all_videos['video_id'] == vid]['channel'].iloc[0]
    df["channel"] = channel_name
    comments_all = pd.concat([comments_all, df], ignore_index=True)
    time.sleep(0.5)

comments_all.to_csv("/content/drive/MyDrive/ANNO2/PRIMO PERIODO 2/SOCIAL MEDIA/PROJECT/comments.csv", index=False)
print(f"\nTotal comments collected: {len(comments_all)}")

Fetching comments for video: JiUoqt4cMrU
Fetching comments for video: LgPQtGMUXAc
Fetching comments for video: bALbBkpC3bc
Fetching comments for video: H-ZzXK0ObNw
Fetching comments for video: BY11cl7ZrC0
Fetching comments for video: mw5Lp52LCcQ
Fetching comments for video: GArK8NOKvzQ
Fetching comments for video: OEEkJSdJJmc
Fetching comments for video: 45d2qQeLjlA
Fetching comments for video: wqNu-w6bHrE
Fetching comments for video: frvkvVXUJ_I
Fetching comments for video: XZu8R3HDOls
Fetching comments for video: 5CkYVLCs0H8
Fetching comments for video: 0mMu0hF1VR8
Fetching comments for video: XkQb5WtvB_w
Fetching comments for video: CHC5xWBT4OE
Fetching comments for video: anqtgX2Ez5k
Fetching comments for video: 0DaTUxr5iHs
Fetching comments for video: _0Puzyktm38
Fetching comments for video: 2PFInd0XfhI
Fetching comments for video: L4OupP_MOCQ
Fetching comments for video: bYQLAyFOz0E
Fetching comments for video: VanW9jeYaTA
Fetching comments for video: 1V6BGv7uH5E
Fetching comments for video: vHzg7XumLto
Fetching comments for video: bh8uHpf87IA
Fetching comments for video: 45O_8uQU7zc
Fetching comments for video: V59q_6Pu3Q0
Fetching comments for video: fEdrIjqZB5c
Fetching comments for video: kf1CWROB5qU
Fetching comments for video: ezgf-bOLpW4
Fetching comments for video: eH_WHiir2lk
Fetching comments for video: DnLgHvFwzL8
Fetching comments for video: eXpD2R1pCmY
Fetching comments for video: z2DqzqthRQI
Fetching comments for video: -v1y8fXJyc8
Fetching comments for video: ZS9Rh_1sJjw
Fetching comments for video: wWd3boPBLC4
Fetching comments for video: G9kyISBD3pA
Fetching comments for video: 1xsQA1X4ALA
Fetching comments for video: m4sf355b3KQ
Fetching comments for video: IoOtC1qTxUk
Fetching comments for video: rUwSX_tth2E
Fetching comments for video: hjhETO2e9gA
Fetching comments for video: LNf0Zow6NmY
Fetching comments for video: TwrAaFien5Y
Fetching comments for video: mYjHZK7cd1s
Fetching comments for video: ntQcz7JGgxg
Fetching comments for video: H23YPfZQqjo
Fetching comments for video: 40zO1xD-oJk
Fetching comments for video: KsDpqlQxZ7Q
Fetching comments for video: _O1V4MTO8Qo
Fetching comments for video: QeuRXlTfhQc
Fetching comments for video: lExdeB36JoE
Fetching comments for video: d3-hCrA0rZw
Fetching comments for video: WRcCqO1WXzk
Fetching comments for video: tvOvbc3uibM
Fetching comments for video: zsVawm2DMUw
Fetching comments for video: z5n-P7yyBlg
Fetching comments for video: yfg35tSOpkg
Fetching comments for video: _imoWbeE3OU
Fetching comments for video: NzXOn_ZPTyQ
Fetching comments for video: 2xXcAbWz8us
Fetching comments for video: b35IO5h0eL4
Fetching comments for video: 0ls5iyR0-k8
Fetching comments for video: M2diCHSBqPs
Fetching comments for video: FQ_YxakrlIA
Fetching comments for video: TlU6rNFFO6s
Fetching comments for video: 6Pzj-9on-vU
Fetching comments for video: gLrYOMwXglU
Fetching comments for video: XXTdX2AHiOo
Fetching comments for video: K16E2wKFxok
Fetching comments for video: RzgDk7atTYI
Fetching comments for video: oWHkGGjCZEw
Fetching comments for video: Mdhb6q7Mrsw
Fetching comments for video: P4FBeG5Snks
Fetching comments for video: bR1vsY0odHM
Fetching comments for video: uepy5BZULoA
Fetching comments for video: WPbvde0NDE4
Fetching comments for video: WbLMrxzlTnU
Fetching comments for video: EG8KGzeXGog
Fetching comments for video: snG4q0KZLNo
Fetching comments for video: JnoIi7hP1kg
Fetching comments for video: uhMr6pG4WB8
Fetching comments for video: JyFwuT7cF1E
Fetching comments for video: JgSeYN9hoCs
Fetching comments for video: w-fRuMpB-rM
Fetching comments for video: ombjaCnG1Wo
Fetching comments for video: GTi1lViCkyQ
Fetching comments for video: M_jwr5VoVR8
Fetching comments for video: a8AyodVEVM8
Fetching comments for video: dQoB_VaVuDo
Fetching comments for video: pOAi_B2OqIQ
Fetching comments for video: NucfBdjHy0g
Fetching comments for video: 5MGWAaabfZI
Fetching comments for video: CfeMfREzyU8
Fetching comments for video: 6zXXOdaE69w
Fetching comments for video: askp779pPnQ
Fetching comments for video: -sQSQaUt3SQ
Fetching comments for video: _mmmdQG0NUA
Fetching comments for video: bcOfsg749Wk
Fetching comments for video: SzwfSetCneU
Fetching comments for video: vp9kfiowltA
Fetching comments for video: 8m3MK7fjvUE
Fetching comments for video: zIgNBj0U6Fw
Fetching comments for video: _b4KHcRXL50
Fetching comments for video: wlxbayQPmTk
Fetching comments for video: Ug9ELAi1bNw
Fetching comments for video: rfAgHpeGdjE
Fetching comments for video: 9ozuPBF5YmM
Fetching comments for video: es5WROjBHjE
Fetching comments for video: 9WpcgTpJkSw
Fetching comments for video: mb4bOyvdU2I
Fetching comments for video: 5aTCf_Lclmc
Fetching comments for video: mIZidz5BEW0
Fetching comments for video: uxtrGYnO4QA
Fetching comments for video: TMz7bxv2baA
Fetching comments for video: qcQpWcZJ6jE
Fetching comments for video: XmyzZPCc2bQ
Fetching comments for video: QwxlBS6HpdY
Fetching comments for video: e_MVA0fQLfE
Fetching comments for video: zhDYV-AZphc
Fetching comments for video: NCfv1cWtpvg
Fetching comments for video: vplvW0aBawM
Fetching comments for video: 3XgO7IqpP3M
Fetching comments for video: o3MH6oxfPhg
Fetching comments for video: MgpiAyajkio
Fetching comments for video: tkmhK7b2qI4
Fetching comments for video: ik3N1uQFjrs
Fetching comments for video: OJyK3bFmRmA
Fetching comments for video: u-8dZ-K62Fs
Fetching comments for video: IuKHUPrH72I
Fetching comments for video: oNRzYAFyJkY
Fetching comments for video: sRevVRMHA4c
Fetching comments for video: UoXYNwcEJFg
Fetching comments for video: ASsMuvu96vM
Fetching comments for video: FK0yGW8QeSY
Fetching comments for video: hZV4_9gZ43A
Fetching comments for video: 14mcUG_V3c0
Fetching comments for video: mt1VvgbQxsQ
Fetching comments for video: rS0n-GjxN0g
Fetching comments for video: nrEM05lijgk
Fetching comments for video: EQ-sRM42Ohk
Fetching comments for video: YRW-oSFko5o
Fetching comments for video: s6yhQhFrZIc
Fetching comments for video: 2w0RxG5g4PI
Fetching comments for video: E5WbhFbPDQY
Fetching comments for video: EN8rN1saxW8
Fetching comments for video: 5Hg866OqQDs
Fetching comments for video: Fv2pv62uXdU
Fetching comments for video: 3RiXf1QBRqQ
Fetching comments for video: ErsnhIohHVU
Fetching comments for video: EsRvcr-l7Sg
Fetching comments for video: Vvb6wTEY5f8
Fetching comments for video: qHU7GRwps3o
Fetching comments for video: imDWemCn3R8
Fetching comments for video: NifaqlYXtRM
Fetching comments for video: 3LMnT7emogc
Fetching comments for video: PEs_FWIE8zc
Fetching comments for video: Pe9J4SiEhyM
Fetching comments for video: LMTZcrs08j8
Fetching comments for video: efCPs2CVKVk
Fetching comments for video: d2ezNAf9vjw
Fetching comments for video: IkiF5jYmG4k
Fetching comments for video: fcy5d-2E0VA
Fetching comments for video: 5ktV2WrVKlw
Fetching comments for video: FrVff3wD4vA
Fetching comments for video: TcatPUqOP0w
Fetching comments for video: hHiLNuVgcas
Fetching comments for video: Y0Lff_Dna7s
Fetching comments for video: 1M_OBdub5xA
Fetching comments for video: LhH2vcnbk98
Fetching comments for video: e82VTT-6gH4
Fetching comments for video: uzM6sRGdIXo
Fetching comments for video: 7XaCK9VqFE8
Fetching comments for video: DiPLTFh1MUM
Fetching comments for video: aWurpkStdhI
Fetching comments for video: MCYh56Wdo5o
Fetching comments for video: dLfbLqlgTZc
Fetching comments for video: 86-FqCIwjsA
Fetching comments for video: VSIZFgnKuDc
Fetching comments for video: _V7-xrWn-ic
Fetching comments for video: RQ0nGppJ5ts
Fetching comments for video: qOT_H4jORAk
Fetching comments for video: ePnigZuCGl8
Fetching comments for video: 1R6U346XB8c
Fetching comments for video: yC3PnVYBTWE
Fetching comments for video: fcXbkRPLPMc
Fetching comments for video: Ll5kqryc4Sc
Fetching comments for video: LIiN6yNLGYE
Fetching comments for video: B4m31m-G0Jc
Fetching comments for video: PyAm-Yd03Xs
Fetching comments for video: rcoYkxR6dY8
Fetching comments for video: 4ihjsRIfe6c
Fetching comments for video: 6L3ew_Y6h5U
Fetching comments for video: jQgC6aglT2k
Fetching comments for video: lCS3OIMFUhQ
Fetching comments for video: Ys0iKKKbSjI
Fetching comments for video: DQt0y0oaIuc
Fetching comments for video: wd80gfVV2R4
Fetching comments for video: wX1QbDjlpYk
Fetching comments for video: iFVQGBEPOMU
Fetching comments for video: 0z_hSyCmRjc
Fetching comments for video: NCnP6-oDYnM

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: 952AVqmi1VY
Error fetching comments for video 952AVqmi1VY: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=952AVqmi1VY&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: h9ACjFqrHzY
Fetching comments for video: Y6NJ4HD6VEQ
Fetching comments for video: i8rGTim-znU
Fetching comments for video: DoEJjU82DQo
Fetching comments for video: UKP7uq65iso
Fetching comments for video: 4ayXk9UVFpY
Fetching comments for video: 1LflA6xdfFU
Fetching comments for video: v2t8SNJr7dk
Fetching comments for video: TwdY-TsNdWY
Fetching comments for video: bm39tf2Bvgs
Fetching comments for video: M03AWi5kgeU
Fetching comments for video: jALL1KEBa9M
Fetching comments for video: 6HTB3myW4dU
Fetching comments for video: WRgjC4ajvOY
Fetching comments for video: 1o2t9xi95fY
Fetching comments for video: RFOMq3jovAc
Fetching comments for video: CYmprWvbwAc
Fetching comments for video: pF4UolBjl3Q
Fetching comments for video: tj0MXm6itCg
Fetching comments for video: Zv6tj_bYvgk
Fetching comments for video: diHFdQ_rb1c

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: ncKrL5vNDlU
Error fetching comments for video ncKrL5vNDlU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=ncKrL5vNDlU&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: elcmGcFGy44
Fetching comments for video: 1TIkpMvPKnk
Fetching comments for video: aWIg8_YI1a0
Fetching comments for video: LStMbbqvyiw
Fetching comments for video: yKlA_Q8Vx0M
Fetching comments for video: 0BQmhhCKcgk
Fetching comments for video: arJNlgsGSak
Fetching comments for video: BihpkTKkYWA
Fetching comments for video: f1FWfjr62hk
Fetching comments for video: 9HrsiwkNObA
Fetching comments for video: G7--BleYnh4
Fetching comments for video: 3C3x-CFFgfc
Fetching comments for video: ApFGcwayKmg
Fetching comments for video: LT5H5dBRgd4
Fetching comments for video: oOZ3doe95ac

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: qCAIGBLYkeY
Error fetching comments for video qCAIGBLYkeY: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=qCAIGBLYkeY&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: BT75YKzT4w8
Error fetching comments for video BT75YKzT4w8: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=BT75YKzT4w8&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: QL4nETkyGVY
Fetching comments for video: Dj3lTCiv6I0
Fetching comments for video: odJblJn3ZL0
Fetching comments for video: xTxSH1MKGq4
Fetching comments for video: xeR9a0gO1FI
Fetching comments for video: k8PpKaI4jCA

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: fHLLvBvdmzQ
Error fetching comments for video fHLLvBvdmzQ: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=fHLLvBvdmzQ&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: T4moeZTvYJg
Fetching comments for video: EBCAnQ7feGA

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: aO_469PJbPw
Error fetching comments for video aO_469PJbPw: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=aO_469PJbPw&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: pao3H5YXvgY

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: jCjcIxlJTPQ
Error fetching comments for video jCjcIxlJTPQ: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=jCjcIxlJTPQ&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: WabLjSCOJjQ
Error fetching comments for video WabLjSCOJjQ: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=WabLjSCOJjQ&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: 9bMXmfM54Gg
Fetching comments for video: KZWD0x0bi70
Fetching comments for video: 83qHj37Y9iE

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: m7cKJaI1-GM
Error fetching comments for video m7cKJaI1-GM: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=m7cKJaI1-GM&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: -bWZsVYxRnI
Error fetching comments for video -bWZsVYxRnI: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=-bWZsVYxRnI&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: 05hu843QRtw
Fetching comments for video: -2Tq-leZgs4
Fetching comments for video: F9Yl4JcjBmY
Fetching comments for video: bGrdPmrjDBQ
Fetching comments for video: yiCQkrXz5IA
Fetching comments for video: BudsC2pcxcc
Fetching comments for video: bR3iVTErfP0
Fetching comments for video: zRgK2yhGSCE
Fetching comments for video: 0KtB2JymdYU
Fetching comments for video: k3hmp_m-xo0
Fetching comments for video: nB2bFEnzf4U
Fetching comments for video: rU6K3dWF1Po
Fetching comments for video: QB6evSCB-JQ
Fetching comments for video: CPnXmMPby58
Fetching comments for video: 2Ln5hNPk_G0
Fetching comments for video: ROYiw3IJgAE
Fetching comments for video: wh_J_ES1YHA
Fetching comments for video: fwAhgy0i_T0
Fetching comments for video: 9HoZIWXEkJk
Fetching comments for video: ruRykcEjD4Y
Fetching comments for video: JZgFUzT31n0
Fetching comments for video: s0sYzaKBUMY
Fetching comments for video: KuUys27o4jo
Fetching comments for video: o1dmu4dmR6k
Fetching comments for video: -k-kDKPwfqg
Fetching comments for video: cc2LzGXkYLM
Fetching comments for video: WCd0Jzvjf0c
Fetching comments for video: TzVmocaJm6Y
Fetching comments for video: 53slvjlDaxQ
Fetching comments for video: NGVju9qI3IM
Fetching comments for video: CBwh8tpMCUg
Fetching comments for video: 8nlr7f9P_yo
Fetching comments for video: JXDJdZE9GVg
Fetching comments for video: gz14qlVpQxw
Fetching comments for video: uJRGUDaaw7s
Fetching comments for video: Hsez6NI_36U
Fetching comments for video: _QB9gJBQXXU
Fetching comments for video: wJb-W7kLYxA
Fetching comments for video: fwL2ooeUsR8
Fetching comments for video: XjI_iE-sNcM
Fetching comments for video: NpEnxhAJywU
Fetching comments for video: y0lX68k2cIc
Fetching comments for video: yXBGFKEDW4o
Fetching comments for video: _GFv73bvxtI
Fetching comments for video: bPQLcvNHK5k
Fetching comments for video: lMFsviUxcJI
Fetching comments for video: MkDAXsF4oXA
Fetching comments for video: Qy0ROog6Uvg
Fetching comments for video: e2Ltdgk9mMU
Fetching comments for video: IuWFVWwesSE
Fetching comments for video: FNuiZ0bChK8
Fetching comments for video: VVzVO0G8vYA
Fetching comments for video: P68aTt3QyvI
Fetching comments for video: cEpuBhLgHV0
Fetching comments for video: nFXr3ufc9X0
Fetching comments for video: ONxfFrycq60
Fetching comments for video: _wgNTtB1tNg
Fetching comments for video: 7vJxJyTWBmc
Fetching comments for video: BoVyH7g4L_8
Fetching comments for video: OU3XdjabWtw
Fetching comments for video: WfM5Lqpka3A
Fetching comments for video: 6Wl8G4k6FoQ
Fetching comments for video: PKCaO7S3pc0
Fetching comments for video: tDhm1Y5Qu50
Fetching comments for video: wP8mQ0hcEhU
Fetching comments for video: ATEhvj9YmWk
Fetching comments for video: 2BjOyJ2Gh8A
Fetching comments for video: yRDek-pGcwE
Fetching comments for video: ISvcAi0mHqk
Fetching comments for video: tY5GnZIm4Ck
Fetching comments for video: 7ms8G2Qd-c4
Fetching comments for video: Y8keOLTGAZA
Fetching comments for video: Xl2uJfjtdZ4
Fetching comments for video: kSOpr8UF9ns
Fetching comments for video: TP6s-LAv1zI
Fetching comments for video: ms4VLCo7niQ
Fetching comments for video: Uv-rBH7hmy4
Fetching comments for video: m-pMLw20Hv0
Fetching comments for video: jWxMrzEXCZE
Fetching comments for video: dNXM3IxMouI
Fetching comments for video: H9Fjzo8-yuA
Fetching comments for video: 9UYp4VPfZMg
Fetching comments for video: nm8awEQT1J4
Fetching comments for video: IUm6s5NaGCw
Fetching comments for video: LoiEMObvVXc
Fetching comments for video: B1MlpEqtoGk
Fetching comments for video: Xykh49sC9Kw
Fetching comments for video: irsArYIXrwc
Fetching comments for video: uoVXEZ3uYGk
Fetching comments for video: bxOplV--ylY
Fetching comments for video: YkYYcZpti_4
Fetching comments for video: pUf9itVdpV0
Fetching comments for video: 0egb6aIY-o4
Fetching comments for video: HEbNkTNSwb4
Fetching comments for video: OlI1O8Hool4
Fetching comments for video: wlNmhD_Elsk
Fetching comments for video: M4vXLypJdCo
Fetching comments for video: W36IqlX3EyA
Fetching comments for video: Rg_I-bqC4m4
Fetching comments for video: nMqgDjak9wQ
Fetching comments for video: gWC0AXBqOLI
Fetching comments for video: nr3Vc6quuTE
Fetching comments for video: a8Ag5MEzw9s
Fetching comments for video: HQvAPaQTZwY
Fetching comments for video: Jq7sfZMMMnA
Fetching comments for video: iMOknjCmUww
Fetching comments for video: bAAAmQcDWCA
Fetching comments for video: sjnpAZVLO70
Fetching comments for video: 7b7iXS2MP-g
Fetching comments for video: s9PrcGxS-UA
Fetching comments for video: 4AbeFndD5xs
Fetching comments for video: rRlyz-Syccs
Fetching comments for video: zCThqYoCJeI
Fetching comments for video: J7wqtded06A
Fetching comments for video: MApkL2hJ_Q4
Fetching comments for video: 6gSSd-wIQ_k
Fetching comments for video: EkvSfcNEtbA
Fetching comments for video: 9Ivsfz81_8s
Fetching comments for video: w-zxISgRdHE
Fetching comments for video: f76zPzRVU4g
Fetching comments for video: a_OecKgUMp4
Fetching comments for video: X-a0v17rYg8
Fetching comments for video: PYrPIjUeqr8
Fetching comments for video: VbAmvZ5SFAA
Fetching comments for video: 7gMshF4wIJc
Fetching comments for video: CL_SiUgk5ko
Fetching comments for video: 0k6gSLAzpXU
Fetching comments for video: DTatfl7vFmo
Fetching comments for video: A-CbdSWXVL0
Fetching comments for video: Uz-Z3wAXm38
Fetching comments for video: zhupqOQqAIw
Fetching comments for video: bfXo8dlLOJQ
Fetching comments for video: j6SidxB-2CU
Fetching comments for video: 1gZBX1QphHU
Fetching comments for video: Mi9qiOe4ezI
Fetching comments for video: hUf2nCC1s_I
Fetching comments for video: R6dgg15dcuo
Fetching comments for video: LwgM8SQLKmg
Fetching comments for video: 0Bqc60wtXyQ
Fetching comments for video: V7XlqTNE3SM
Fetching comments for video: ddkZO6QaNeU
Fetching comments for video: zGjvhLr82Yc
Fetching comments for video: bh-NoouZEas
Fetching comments for video: F7T4lu4p7Gk
Fetching comments for video: XIVvhGGxU98
Fetching comments for video: RTtEV1_fG9c
Fetching comments for video: aL0ndJ8eRxU
Fetching comments for video: IzMkmcVavGg
Fetching comments for video: 26VdNRi1kkQ
Fetching comments for video: hi2oIidckBA
Fetching comments for video: nF8wLBE3yLw
Fetching comments for video: j9GIKrJLOXM
Fetching comments for video: TLrZu0VavQc
Fetching comments for video: 1C0OclnjTQg
Fetching comments for video: PKr3BAA_H-w
Fetching comments for video: v3yiEuPzPvA
Fetching comments for video: SS3fsnxpwEI
Fetching comments for video: sJJOqTBdrOI
Fetching comments for video: DxM3g9KyITQ
Fetching comments for video: GhRjaSmRAq0
Fetching comments for video: d4ZVcO_oz1E
Fetching comments for video: SQ6WG_KMyqw
Fetching comments for video: dhfEZpCSv-k
Fetching comments for video: 8JfUILK-cro
Fetching comments for video: 71vGIzyEe5c
Fetching comments for video: o5feeh4_xuo
Fetching comments for video: t0jMv4Rk8Mw
Fetching comments for video: 0L937gV7YZ4
Fetching comments for video: k6HZRtvgkws
Fetching comments for video: nsqM8ihqMXo
Fetching comments for video: cmnru0H1JlI
Fetching comments for video: lfryBMVa2Xo
Fetching comments for video: gFtYajSJK3s
Fetching comments for video: HmFOjKs1rRE
Fetching comments for video: zQ4dwl80glU
Fetching comments for video: vVvhEDeeml4
Fetching comments for video: 4C3CXQrsFPw
Fetching comments for video: fzzagyDw0BA
Fetching comments for video: TqncV6f23XA
Fetching comments for video: ilgJQsv2LDU
Fetching comments for video: peWIO9kVeWE
Fetching comments for video: hFRe7Veayok
Fetching comments for video: PijN5t7a4o0
Fetching comments for video: d6rZtgHcbWA
Fetching comments for video: RSEv4GCunws
Fetching comments for video: L_BnuNChE-k
Fetching comments for video: oIwb-Kis7Qg
Fetching comments for video: TUx2R9ZgjgI
Fetching comments for video: n397ptYRJZs
Fetching comments for video: X5TqzKG81Vg
Fetching comments for video: XFH8aGBjA6U
Fetching comments for video: ufe0FuTL298
Fetching comments for video: YlAuHZsFmhU
Fetching comments for video: epfZJu5JkP4
Fetching comments for video: 3ObIEBkssuU

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: gJPk7rcjfpw
Error fetching comments for video gJPk7rcjfpw: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=gJPk7rcjfpw&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: emjET20ZSsQ
Fetching comments for video: r7MRGRXtHkc
Fetching comments for video: pxpSzn7iNXI
Fetching comments for video: fd-PSSN_cA0
Fetching comments for video: jWT74pNljxY
Fetching comments for video: TNR2XD9WXhM
Fetching comments for video: 4X3MoZZWLA8
Fetching comments for video: xwZYQx_Xubs
Fetching comments for video: gqfrtKjAUsk
Fetching comments for video: eWI4hO13rUA
Fetching comments for video: jmbXBbvVYKA
Fetching comments for video: 8ZxuUxo4HVk
Fetching comments for video: Nj5KkzIzOo8
Fetching comments for video: f23hv1zXN8I
Fetching comments for video: M8JZostpsEU
Fetching comments for video: L9vvPKnPivk
Fetching comments for video: lryW6Ksk8IQ
Fetching comments for video: sE4wp6MP3Sk
Fetching comments for video: znwdKE6xlwA
Fetching comments for video: HClranfeT5Q
Fetching comments for video: 3Sw8FRByM6c
Fetching comments for video: S1O48ioVFb0
Fetching comments for video: BFVfUiKnx1Q
Fetching comments for video: fLMO2j5uq4k
Fetching comments for video: U3b8ZFaB5Vw
Fetching comments for video: CDFcMc0OHx0
Fetching comments for video: FElXfOQEOyY
Fetching comments for video: p15nqtk0-28
Fetching comments for video: 4UGuo8FGpKA
Fetching comments for video: DSbWRvKyIuE
Fetching comments for video: pejLr9UEWoU
Fetching comments for video: _T2dCI_uRnc
Fetching comments for video: 7_UHhBAj6iE
Fetching comments for video: YUTokdV2edg
Fetching comments for video: 7OjVYUmP_zw
Fetching comments for video: 7QFl5utGTV8
Fetching comments for video: vPaF6TypfX8
Fetching comments for video: p9SerdKyxsw
Fetching comments for video: fUmi1h0db0k
Fetching comments for video: GN-PsJJ864I
Fetching comments for video: FkLhgqTd99M
Fetching comments for video: JlMnmKpp89M
Fetching comments for video: 5OjGkUl-FUQ
Fetching comments for video: OE-ZA9UtZBo
Fetching comments for video: lO31gu0HVT0
Fetching comments for video: WDLYCTLdeVM
Fetching comments for video: GcEO0wFLkiY
Fetching comments for video: PsYYjG8Y58I
Fetching comments for video: LSNf2Mu48BA
Fetching comments for video: ZptFHx5hcwI
Fetching comments for video: q1uEzo_X8GU
Fetching comments for video: FZeesfDuCWw
Fetching comments for video: apJlfwDOhUI
Fetching comments for video: o6Qo-ie0nbE
Fetching comments for video: QJEAJs2yPmw
Fetching comments for video: dnuSEkDcoK4
Fetching comments for video: TtYWV4v4b9I
Fetching comments for video: 3VHEuS41Hk8

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: 6YK-KysXrvs
Error fetching comments for video 6YK-KysXrvs: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=6YK-KysXrvs&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: tDwTyQNAICg
Fetching comments for video: KBM_FlHv83A
Fetching comments for video: JUZc-GGi9tw
Fetching comments for video: bh6-ugcN-zk
Fetching comments for video: itysjwi8t64
Fetching comments for video: XT0waFxGkEk
Fetching comments for video: sSlFoLn0fvA
Fetching comments for video: ka3RnEKCwWM
Fetching comments for video: ZZ2WS6AI_SM
Fetching comments for video: LvwP1s7okDY
Fetching comments for video: PlbEJteWMGk
Fetching comments for video: KG1tlhu6614
Fetching comments for video: PlZOVmwRQr0
Fetching comments for video: RomywAljLjo
Fetching comments for video: fuPQrmccekc
Fetching comments for video: gev1dXzbi6s
Fetching comments for video: fPzauiWsIK8
Fetching comments for video: gb-ljOXzpYs
Fetching comments for video: 9EMtLUYj_Co
Fetching comments for video: W8oW9LwHQKQ
Fetching comments for video: aiqb9cz3yUo
Fetching comments for video: cL98lYPS8B4
Fetching comments for video: nkXkRNVrIvM
Fetching comments for video: RwIspUe78Bg
Fetching comments for video: EczqWXF_ch0
Fetching comments for video: c9MMmzyMQkI
Fetching comments for video: P_2Zfaxfptk
Fetching comments for video: ToZQDk3AmZs
Fetching comments for video: BuQC8lKCZCI
Fetching comments for video: v5kQ7kWiZv0
Fetching comments for video: tgob38AlhV4
Fetching comments for video: B1-qr-PnT9Q
Fetching comments for video: jAEUSvORGy4

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: iQ8jZyRLOE0
Error fetching comments for video iQ8jZyRLOE0: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=iQ8jZyRLOE0&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: ZKRY827SCew
Fetching comments for video: 8OS-j7SjYEw

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: SoVstwthMVw
Error fetching comments for video SoVstwthMVw: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=SoVstwthMVw&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: qn7JIY6Mj-k
Fetching comments for video: FoAM4Behofs
Fetching comments for video: odBjF3KNNmI
Fetching comments for video: Cv6QBEgSDWc
Fetching comments for video: 8hj5exFj3Bk
Fetching comments for video: USCotn9WVy0
Fetching comments for video: UQMshpUMepw
Fetching comments for video: oIZRpcsIrhA
Fetching comments for video: DPIWNOfGErc
Fetching comments for video: jwI_kkbhlzo
Fetching comments for video: aMIlIbY9VRE
Fetching comments for video: 6wTe2JJmcRk
Fetching comments for video: p9ONnNFdNtQ
Fetching comments for video: qHkJ7y1j264
Fetching comments for video: K59wJVhyHj4
Fetching comments for video: S95jRLfYTH4
Fetching comments for video: VljPiFfmjUc
Fetching comments for video: l6CZ7WuomRg
Fetching comments for video: LpyQyaVANMI
Fetching comments for video: 8s-bE7GMFkg
Fetching comments for video: fTXemyx1vNw
Fetching comments for video: Lc14XvRlDb0
Fetching comments for video: 0oG0pJNVHJY

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: MJ8CKiZO56Y
Error fetching comments for video MJ8CKiZO56Y: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=MJ8CKiZO56Y&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: 8EmXwrebAxs
Fetching comments for video: WKbNcwoIs7o
Fetching comments for video: cjUO4jiNONc
Fetching comments for video: OcyFZEdt35s
Fetching comments for video: LoXwBzv513Q
Fetching comments for video: s3QPt_DTzHw

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: L6pt9-JDDIA
Error fetching comments for video L6pt9-JDDIA: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=L6pt9-JDDIA&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: l7cEmYBCoNc
Fetching comments for video: sjy6Pqr__8w
Fetching comments for video: EO3hZNHEcSY

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: 3pKXDAe6E5Q
Error fetching comments for video 3pKXDAe6E5Q: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=3pKXDAe6E5Q&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: VCQz2eDtA68

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: YPtbr3gZAVM
Error fetching comments for video YPtbr3gZAVM: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=YPtbr3gZAVM&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: xO3dRFjmxjU
Error fetching comments for video xO3dRFjmxjU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=xO3dRFjmxjU&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: dSo8rVSbi-Q
Error fetching comments for video dSo8rVSbi-Q: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=dSo8rVSbi-Q&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: 26IXB4GVEjA
Error fetching comments for video 26IXB4GVEjA: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=26IXB4GVEjA&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: XGsW4mHDRKU
Error fetching comments for video XGsW4mHDRKU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=XGsW4mHDRKU&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: zyyQV2Rtw38
Error fetching comments for video zyyQV2Rtw38: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=zyyQV2Rtw38&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: vYqP-3ijl-8
Error fetching comments for video vYqP-3ijl-8: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=vYqP-3ijl-8&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: lvGa2whcIys
Error fetching comments for video lvGa2whcIys: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=lvGa2whcIys&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: f_GrFzw8CVY
Error fetching comments for video f_GrFzw8CVY: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=f_GrFzw8CVY&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: EjNVrHDtuEw
Error fetching comments for video EjNVrHDtuEw: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=EjNVrHDtuEw&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: 3VB5WsryYjE
Error fetching comments for video 3VB5WsryYjE: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=3VB5WsryYjE&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: 7NQRtP6A0OM
Error fetching comments for video 7NQRtP6A0OM: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=7NQRtP6A0OM&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: i7fC-Jf2V2g
Error fetching comments for video i7fC-Jf2V2g: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=i7fC-Jf2V2g&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: _vQrkj3xSiA
Error fetching comments for video _vQrkj3xSiA: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=_vQrkj3xSiA&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: r00zeZIYNj0
Error fetching comments for video r00zeZIYNj0: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=r00zeZIYNj0&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: sxXvSfTcyeU
Error fetching comments for video sxXvSfTcyeU: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=sxXvSfTcyeU&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: lBHI3uTTxS4
Error fetching comments for video lBHI3uTTxS4: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=lBHI3uTTxS4&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: IaO2eWVZ79U
Fetching comments for video: VB2eRwOp_Ck
Fetching comments for video: NezUCGnirSs
Fetching comments for video: 59H7sC1vLes
Fetching comments for video: 13SwFGUy2LA

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: Q2Vs43jjZFs
Error fetching comments for video Q2Vs43jjZFs: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=Q2Vs43jjZFs&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: iIErgFmZ9sk
Fetching comments for video: cddBjUWdk_w
Fetching comments for video: LB2fT1siDtc
Fetching comments for video: QF-6YgwDU30
Fetching comments for video: Tl2eZZz75ok
Fetching comments for video: X1B-nyChiOA
Fetching comments for video: 6RYPXsU3_i4
Fetching comments for video: 50hKyJGaFBg

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: ZqQ07Vcv_-c
Error fetching comments for video ZqQ07Vcv_-c: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=ZqQ07Vcv_-c&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: q3HhH3fLHi8
Fetching comments for video: mMvi_H36VPQ
Fetching comments for video: F10CxIiLeME
Fetching comments for video: j3cWJmfC_Jg
Fetching comments for video: NRxHOG8JsTQ
Fetching comments for video: tuewjQuaWF0
Fetching comments for video: 1auaxieiEdM
Fetching comments for video: MD96tGW88ho
Fetching comments for video: ESWHstZjle8
Fetching comments for video: 1FcRWztkWj4
Fetching comments for video: -otZsibpfn4
Fetching comments for video: 6sqKnxKPiSU
Fetching comments for video: MbEC58Le0cM
Fetching comments for video: Jxf1L4fVrB4
Fetching comments for video: fxoUaL9IKuo
Fetching comments for video: 0c1wzSDVACo
Fetching comments for video: HwCp5h4SH3o
Fetching comments for video: Z3gvYMd2bY8
Fetching comments for video: LsMjXJb9PUE
Fetching comments for video: Zo2FaOJ6ZPQ
Fetching comments for video: L7GgxKw8un0
Fetching comments for video: Lkq06snGce8
Fetching comments for video: iDJkIKX5ngk
Fetching comments for video: icoNCo5Za_0
Fetching comments for video: ldQyCiRmsjY
Fetching comments for video: pe248MAg9TQ
Fetching comments for video: mppJaqQKflY
Fetching comments for video: -4B_9Tv0ZcI
Fetching comments for video: eM_w4IUeeGI
Fetching comments for video: d-93oTe4dG8
Fetching comments for video: _mmICzBuowI
Fetching comments for video: ykF1AcZB_1c
Fetching comments for video: swF-r2pjYsQ
Fetching comments for video: 2wabjEP-GjQ
Fetching comments for video: 5Negw4ffK_4
Fetching comments for video: QpaCL_6Y2D4
Fetching comments for video: GY56KSj-4Lo

WARNING:googleapiclient.http:Encountered 403 Forbidden with reason "commentsDisabled"

Fetching comments for video: ksNYpfmc_LM
Error fetching comments for video ksNYpfmc_LM: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/commentThreads?part=snippet&videoId=ksNYpfmc_LM&maxResults=100&textFormat=plainText&key=AIzaSyDdgU6rDfbSZRJvaOdxUBs-bAIuJmpXSu4&alt=json returned "The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.". Details: "[{'message': 'The video identified by the <code><a href="/youtube/v3/docs/commentThreads/list#videoId">videoId</a></code> parameter has disabled comments.', 'domain': 'youtube.commentThread', 'reason': 'commentsDisabled', 'location': 'videoId', 'locationType': 'parameter'}]">
Fetching comments for video: toist6_jMyA
Fetching comments for video: 3w0VR0omNgk
Fetching comments for video: rHQQU4-oiMk
Fetching comments for video: NLq4DY9N5NA
Fetching comments for video: ewi8FD-Wh0w
Fetching comments for video: K9x1d2--p1Y
Fetching comments for video: fsvV6B47F3E
Fetching comments for video: B125A1vrBYc
Fetching comments for video: 8-D84_vZ80s
Fetching comments for video: OFiNpeyshzE
Fetching comments for video: jVDwjG7TA38
Fetching comments for video: qEk_za2_9BU
Fetching comments for video: XmYmSHvSb_M
Fetching comments for video: 74INJWr18xk
Fetching comments for video: D_6_S7Gzoy8
Fetching comments for video: lCUY2l8YSLE
Fetching comments for video: a47xK5bM_Do
Fetching comments for video: g2-v8ql6F-M
Fetching comments for video: gpgIO6iUuoA
Fetching comments for video: -zq2x-Tm7dI
Fetching comments for video: 120DqRMsGGk
Fetching comments for video: lCiuHClRgng
Fetching comments for video: DVh4w8-xJ0A
Fetching comments for video: zrkr41Y6xOo
Fetching comments for video: QS9im4o-l60
Fetching comments for video: -INkLY2W_tU
Fetching comments for video: lnrvgrE89c4
Fetching comments for video: GkE5jyJ1r04
Fetching comments for video: lLp0fRaHUWY
Fetching comments for video: wjAXxxWEz_Q
Fetching comments for video: Qpp0_kGm_tg
Fetching comments for video: 1ZHxiOZEev8
Fetching comments for video: g3uQsPxveT8
Fetching comments for video: lRu00MsQ9VI
Fetching comments for video: bGVm3l7KM3A
Fetching comments for video: muI2y5lKbCQ
Fetching comments for video: ZIja6ksdRBM
Fetching comments for video: y5RVYRNzd3A
Fetching comments for video: oXYJ-zayUMw
Fetching comments for video: aaGCZsymYz8
Fetching comments for video: Br2yLtauuac
Fetching comments for video: YdIvtm-UfkU
Fetching comments for video: 4NTKY9cF2-0
Fetching comments for video: T-UL_rEH1WQ
Fetching comments for video: t2Lv6f4Tsxs
Fetching comments for video: gav95w0pdhs
Fetching comments for video: NYSv-xsNBec
Fetching comments for video: NtAHG4LRvbg
Fetching comments for video: 9ff-GDeM1FE
Fetching comments for video: zmuRmVAu324
Fetching comments for video: kYnsn0KrhCw
Fetching comments for video: u-WIdZMgpIY
Fetching comments for video: 129swAboqWg
Fetching comments for video: WCG5DE_PBsw
Fetching comments for video: wL1pLoaEawU
Fetching comments for video: HeaLn2YZeA0
Fetching comments for video: g_aDbXhJQ-U
Fetching comments for video: JmEaX5NlSV0
Fetching comments for video: 3064pA8G36I
Fetching comments for video: 2sIzLPVxUkw
Fetching comments for video: B0B7KZZQ7eQ
Fetching comments for video: nunLvNGbCDE
Fetching comments for video: G99qJJBJtXM
Fetching comments for video: RrnmhSq-zqg
Fetching comments for video: 3Ws4NsFC1LA
Fetching comments for video: LEBXeZPDjaA
Fetching comments for video: -s5iENW1zNY
Fetching comments for video: xoXzmFRuhAQ
Fetching comments for video: n3AyIbtLQ5o
Fetching comments for video: HS_-K4b-aYE
Fetching comments for video: Ou5AhQWTex0
Fetching comments for video: PR7QdBw8G3g
Fetching comments for video: Mvm0BGGgJ0Y
Fetching comments for video: ktuHYgyctCc
Fetching comments for video: R-3ZjMU5_p4
Fetching comments for video: w8tBfFg38Qk
Fetching comments for video: lUegsCFnuig
Fetching comments for video: t1cD8wOaM4k
Fetching comments for video: Orup6m9j7hw
Fetching comments for video: mQJlzENr9f0
Fetching comments for video: rQGIwnX64Go
Fetching comments for video: DOIoims2VLg
Fetching comments for video: iFXVsB-xe5M
Fetching comments for video: 9y4C9SgzlS4
Fetching comments for video: dFUq9X859Q4
Fetching comments for video: _IqYJNwT9Po
Fetching comments for video: -n4rtqm076I
Fetching comments for video: Bgrfsaekpo8
Fetching comments for video: 2TeyA7A4KVU
Fetching comments for video: z3wRFMVVA8U
Fetching comments for video: VBqNKVbmpF8
Fetching comments for video: 4WgxWlcf1Xw
Fetching comments for video: dr9O6b4f9tY
Fetching comments for video: g9TElZ8DsNE
Fetching comments for video: tidejP41CBk
Fetching comments for video: eUATziI8hwE
Fetching comments for video: a08VQPYbwsM
Fetching comments for video: 83NZz0EtEy4
Fetching comments for video: y9O8u5Xu85Y
Fetching comments for video: SE83sCuYA4c
Fetching comments for video: s1SUB_UztJ0
Fetching comments for video: QdcoDUGLe14
Fetching comments for video: t7KTbzUXETg
Fetching comments for video: zJBgW2Y9-6M
Fetching comments for video: O9QWvH40kNY
Fetching comments for video: oD0ZFQiCisA
Fetching comments for video: ht_LRDARA54
Fetching comments for video: Rf42nLsXLTI
Fetching comments for video: 3tbUIJihpLM
Fetching comments for video: ZOOLUUTBy34
Fetching comments for video: bS3eHOOQElE
Fetching comments for video: K1hZUuGtO4A
Fetching comments for video: AKrQ0ZeqpZs
Fetching comments for video: apseHD6BsCs
Fetching comments for video: pA48gVurn4A
Fetching comments for video: jEPK7XYKpTg
Fetching comments for video: 1WwJy2JhjMw
Fetching comments for video: bz_rc8AZyyw
Fetching comments for video: SCBHvYyPDj0
Fetching comments for video: s-tamH1yZc0
Fetching comments for video: SOGFeb50Y7M
Fetching comments for video: XLzSdLbL-YQ
Fetching comments for video: ZrywbsApCRo
Fetching comments for video: NKaOStlrR40
Fetching comments for video: cY9QY_6aXeI
Fetching comments for video: pxBC6RABAH4
Fetching comments for video: eJzL5u4Y110
Fetching comments for video: Mhx_FaokzRE
Fetching comments for video: UsDtaQJ8b6g
Fetching comments for video: cqb4jODQvFw
Fetching comments for video: KYxBTn4ncCE
Fetching comments for video: nzgsTacnjzk
Fetching comments for video: 3QWl477JYoQ
Fetching comments for video: w1F42XhbS1A
Fetching comments for video: AJOfbtw1VNo
Fetching comments for video: mUG4phlluS4
Fetching comments for video: WKbvzsoWKRg
Fetching comments for video: WyvRvkZnXSE
Fetching comments for video: wr1itEquo8E
Fetching comments for video: sOhYUv7RFCM
Fetching comments for video: 5VRZ_DtOx58
Fetching comments for video: iMbohPhE6IE
Fetching comments for video: FwmuggSrKqA
Fetching comments for video: J58u5-3XFV8
Fetching comments for video: 3qKdVAM_uNI
Fetching comments for video: KZ_YF6SbtSg
Fetching comments for video: xUXY7y7cDNU
Fetching comments for video: 6ohqkMsXj9w
Fetching comments for video: 2umk3J4E1UY
Fetching comments for video: FFag3_Eumlo
Fetching comments for video: qRkW9rPmfrY
Fetching comments for video: kTjRN9L4Sto
Fetching comments for video: USW_2zzOWow
Fetching comments for video: HmLymPdr_Q0
Fetching comments for video: bP1I7a8hNME
Fetching comments for video: _ORe0hWzjk0
Fetching comments for video: CvmwJfTXdd4
Fetching comments for video: xf0WZWL-fb4
Fetching comments for video: ML2-Nd5OWKo
Fetching comments for video: -V1qgihp9J8
Fetching comments for video: D2nd8Lf0scs
Fetching comments for video: C_KUM_Iae6I
Fetching comments for video: aa6HwSxsNxE
Fetching comments for video: DAhV2WArKr8
Fetching comments for video: 1sA-bK4qfMU
Fetching comments for video: 5qBDQgfeB6s
Fetching comments for video: GFPMpF8G9xQ
Fetching comments for video: HYYoepuLZSI
Fetching comments for video: epTbXemWO9g
Fetching comments for video: zJHYVzB4Nu0
Fetching comments for video: 6_rhNgOuM0s
Fetching comments for video: 63074aTEBzg
Fetching comments for video: V91VpX52Dqs
Fetching comments for video: kjKPsv9fNLA
Fetching comments for video: u95-PjoAwRU
Fetching comments for video: TXKPKCdqAew
Fetching comments for video: -n5MYIea8_A
Fetching comments for video: lzM8pV6ISJM
Fetching comments for video: 0CL2HGwWyBU
Fetching comments for video: OChc9EQ-b2w
Fetching comments for video: gAo36nC5ly8
Fetching comments for video: ClCGUMn6eHw
Fetching comments for video: airkjnJ7dDs
Fetching comments for video: TYdScXghFZc
Fetching comments for video: qJCC-69g3mg
Fetching comments for video: ivJTEEfL2_8
Fetching comments for video: Y1HNa_XhTN4
Fetching comments for video: ozi5xZ67GVA
Fetching comments for video: 6TvWtR49FgA
Fetching comments for video: PJlUPcEDq3c
Fetching comments for video: PoS2BRIHP4Y
Fetching comments for video: Daf7v90vcOY
Fetching comments for video: lp6CXArlCao
Fetching comments for video: hHW1V7tH-hg
Fetching comments for video: kNF9WtkkMKE
Fetching comments for video: aSmmEio6gDM
Fetching comments for video: rxUKF6ZNZHo
Fetching comments for video: 5GFcKRn_DJg
Fetching comments for video: vGSbkqck0q8
Fetching comments for video: czKI2rSA8xw
Fetching comments for video: 5QN3hHy0pdU
Fetching comments for video: 6EfOvyZPej4
Fetching comments for video: IbR6avc6_KI
Fetching comments for video: hJMtSxAM5SU
Fetching comments for video: Sum2mDifaho
Fetching comments for video: Q7qlW7i2dK4
Fetching comments for video: XFmsvt_dffw
Fetching comments for video: yAgcKZ5MYHA
Fetching comments for video: QpcpBZMS6do
Fetching comments for video: 2UFI28AiMsI
Fetching comments for video: sV0EpoqtVoA
Fetching comments for video: o6hNBH40oB0
Fetching comments for video: ODmIJr2jmpY
Fetching comments for video: EVUF5SkR4HI
Fetching comments for video: ougk5liAA30
Fetching comments for video: GGF-NvTrkq4
Fetching comments for video: iWrSx-1ajgo
Fetching comments for video: JyFHDTrcZhE
Fetching comments for video: lL5HSEjYrMM
Fetching comments for video: gQ7tFlCvXVU
Fetching comments for video: 5ETpu3PVEGs
Fetching comments for video: dcm68a0a1j4
Fetching comments for video: 5BnzpjAj1LU
Fetching comments for video: Fb4YR7hs65c
Fetching comments for video: cjaaNjQIPfI
Fetching comments for video: k3iC-dk4SgA
Fetching comments for video: MOHKTjmtLsY
Fetching comments for video: aprCvKGrLYw
Fetching comments for video: Key23rzPPyc
Fetching comments for video: Mjzh_lghnq4
Fetching comments for video: l6rQoG41zXM
Fetching comments for video: hYJEPOoaIh4
Fetching comments for video: RXlOGodSy1E
Fetching comments for video: 7EtiWeTArL8
Fetching comments for video: Dzo90Al8pE8
Fetching comments for video: rsNlluQENFs
Fetching comments for video: JBCmXkF_ynk
Fetching comments for video: 6oyP9yAdZZY
Fetching comments for video: QTwKGYb8q4M
Fetching comments for video: Pmr0KMGVSAU
Fetching comments for video: 4SzXhD1o3fA
Fetching comments for video: dpwt_pzC_Io
Fetching comments for video: A0GswZ_Nd_4
Fetching comments for video: bi2RpVnfb28
Fetching comments for video: uDPDmtcLvhY
Fetching comments for video: SXXaO1UDd9A
Fetching comments for video: 08bJX8roIsY
Fetching comments for video: sOu43hmKbDs
Fetching comments for video: XrSSjbMgu94
Fetching comments for video: -e2NGbF1OnY
Fetching comments for video: p7fGAgzOvcg
Fetching comments for video: NaywMz6RChk
Fetching comments for video: PxEbdpMMa24
Fetching comments for video: wkmjScTq1Ps
Fetching comments for video: fJH2JHULByQ
Fetching comments for video: OhBds0177I4
Fetching comments for video: U4_Qo4LA_48
Fetching comments for video: 9ZQSIUydXNU
Fetching comments for video: JhutOT0wSII
Fetching comments for video: d_ougHAugow
Fetching comments for video: 2Vvi3BqTIu0
Fetching comments for video: l8lMpImM29g
Fetching comments for video: OyAl5Ch-tK8
Fetching comments for video: NKBqo5FLc8c
Fetching comments for video: AlZ6FZSl-xY
Fetching comments for video: 10TIu1_olBY
Fetching comments for video: QE4mAjhaL6A
Fetching comments for video: UmPjTN_b6L8
Fetching comments for video: tvK7ECjIwMI
Fetching comments for video: lLTLHGrtTww
Fetching comments for video: C7J5uDEBI2w
Fetching comments for video: fCJumOYVeO4
Fetching comments for video: R1qOso19iuA
Fetching comments for video: ST6Zdqxj0Ko
Fetching comments for video: it5IiMSjJpM
Fetching comments for video: Pu-0Qb_dxhM
Fetching comments for video: cgYAQZlrPK8
Fetching comments for video: CoUWh8jp1qY
Fetching comments for video: nObgUv0Q_Tc
Fetching comments for video: r5rndR38GYo
Fetching comments for video: xc6Xv41eP88
Fetching comments for video: h3WL0Dm25Es
Fetching comments for video: s_pm3SU1gsg
Fetching comments for video: 2drF_VP6VGA
Fetching comments for video: gvyOKVT9FpY
Fetching comments for video: 2e8el8lyp1c
Fetching comments for video: NhSqT9QPD3Y
Fetching comments for video: lz0Yb4jCRjM
Fetching comments for video: XzS1TGmL23I
Fetching comments for video: _8HPJB9mz1s
Fetching comments for video: H0yvoL1i6VM
Fetching comments for video: D-0-C__TtyI
Fetching comments for video: 1z7C_2XzaDE
Fetching comments for video: F1MfuRflVcs
Fetching comments for video: xXZ84hWnRdI
Fetching comments for video: oG2eNmBT3uw
Fetching comments for video: c7h5Tf91gn0
Fetching comments for video: -OBh3Wyl8Q4
Fetching comments for video: onwJ0ZmT7qM
Fetching comments for video: euvU4dI-gRc
Fetching comments for video: aBevPgnHOFA
Fetching comments for video: lSixG_-AwMA
Fetching comments for video: ZTMbtm7WUdI
Fetching comments for video: cpRFL29vHds
Fetching comments for video: R_jlPjKUG_Y
Fetching comments for video: hYoi1ADN3as
Fetching comments for video: GDBJHJ_AiiQ
Fetching comments for video: Jj4pCJa4JCM
Fetching comments for video: Dj99_Q9bE18
Fetching comments for video: OMBxolu127k
Fetching comments for video: Nlf3uWCuejk
Fetching comments for video: k4yHyiqQLMU
Fetching comments for video: f_N_rpqLc8Y
Fetching comments for video: W7kGUwsl5VE
Fetching comments for video: voUSCxGAb7A
Fetching comments for video: 0X3oSi7zhzY
Fetching comments for video: NHnxbvBamvE
Fetching comments for video: -3HxiCU-cNs
Fetching comments for video: SCSvrjX0_Sw
Fetching comments for video: c0Tw29Xi9p0
Fetching comments for video: vqSelUwW-cA
Fetching comments for video: YUgIbMwxyLI
Fetching comments for video: PAgq6EPPUOY
Fetching comments for video: q3JOOgF1Y14
Fetching comments for video: x2lqZeNJr0E
Fetching comments for video: lBKeh58aZwU
Fetching comments for video: l2S5vKQCSrI
Fetching comments for video: zDGh2TQDKCw
Fetching comments for video: jb_VYpd37zw
Fetching comments for video: oGD2FJ3MzJk
Fetching comments for video: aQJckN3FJK8
Fetching comments for video: _teWS8pqRPk
Fetching comments for video: QC8840zX5J0
Fetching comments for video: 75fm6INauZE
Fetching comments for video: YdsAA-SbrlA
Fetching comments for video: zh9qXS-5tgI
Fetching comments for video: M2FOTkPKfHA
Fetching comments for video: PUsArr6bfL8
Fetching comments for video: HTOOXVi8h_c
Fetching comments for video: dgUD0fXfi2Q
Fetching comments for video: CJ2H5EUPsV8
Fetching comments for video: N-NoJbjEN2U
Fetching comments for video: 3PNK0UxIBdA
Fetching comments for video: NxUz-jdJNTE
Fetching comments for video: cqHWIt8KHns
Fetching comments for video: nYP8ILczGAU
Fetching comments for video: qyzxFy5ZRCo
Fetching comments for video: UjblDPfBk24
Fetching comments for video: JZyy_TRbEG4
Fetching comments for video: 8S3HuvmbmkM
Fetching comments for video: xXSB4oOl_zw
Fetching comments for video: e9QnFDwj_8w
Fetching comments for video: d7epXyNlJk0
Fetching comments for video: NNv10PDAG9k
Fetching comments for video: IqtUPJbFbP0
Fetching comments for video: F_0LYlJvbqI
Fetching comments for video: MBOskX80Q4o
Fetching comments for video: 2OJQCZTVnPw
Fetching comments for video: DTNOD9FI6JE
Fetching comments for video: RahDTD76dDQ
Fetching comments for video: VNR5VIwF1yE
Fetching comments for video: eajp86ZolRg
Fetching comments for video: dqajUxyxOIc
Fetching comments for video: DPjC3xfYK04
Fetching comments for video: CKCRcdv7aGc
Fetching comments for video: 831g5v87WYA
Fetching comments for video: RQXpQZaYyMM
Fetching comments for video: nlc828IhNI4
Fetching comments for video: 4KN8DyIvcTI
Fetching comments for video: 0AQvjUhV6Lk
Fetching comments for video: Lz4kioS28rY
Fetching comments for video: 52_9-eNPk1U
Fetching comments for video: cCiRJ85CtSE
Fetching comments for video: 5jbqyWybU3Q
Fetching comments for video: MPTZJXCMSi4
Fetching comments for video: d0vg-rNsueg
Fetching comments for video: XVOP2L9RgPk
Fetching comments for video: H5FHCwKBrIk
Fetching comments for video: p2OIySYiNgo
Fetching comments for video: 6kvbgN2uDmU
Fetching comments for video: ZdkHXVfyC9M
Fetching comments for video: qFdbP24HNyk
Fetching comments for video: 86YPXL_hqSM
Fetching comments for video: PIy4a9QgPqE
Fetching comments for video: hDVtpMj2Udw
Fetching comments for video: 3JbRcP6m1VI
Fetching comments for video: KcO8b6n_ULw
Fetching comments for video: 8zYBIFFNu4w
Fetching comments for video: Tsyu0SQWpo4
Fetching comments for video: JMW33I7Mf8c
Fetching comments for video: TWKwDXNGQdM
Fetching comments for video: rB4y_pOhUZg
Fetching comments for video: gw9UyOGsF4s
Fetching comments for video: 7LaVcL_12I4
Fetching comments for video: GNqHEDZ1x0o
Fetching comments for video: oylbyE5Zt0Q
Fetching comments for video: e478dy0CKYE
Fetching comments for video: KjYSHrFkGrU
Fetching comments for video: xD3Qm3Gl5uE
Fetching comments for video: 2vRLc0SEEJY
Fetching comments for video: -u40Rg-9t54
Fetching comments for video: f6uADmg-4OE
Fetching comments for video: BSU3sRNOhIg
Fetching comments for video: d-qNPfXiobI
Fetching comments for video: -jjswjC-Onk
Fetching comments for video: EwfguyrpW6Y
Fetching comments for video: cKlI4gz5Tgk
Fetching comments for video: hiNaP0UP0jg
Fetching comments for video: jMu2opMqTeE
Fetching comments for video: NDJONvjeHBU
Fetching comments for video: qyo50CHjsvU
Fetching comments for video: C31ELGDkLw4
Fetching comments for video: R347hVdMRmY
Fetching comments for video: _YeWRRqW520
Fetching comments for video: aGN8oy1xa-Y
Fetching comments for video: heSKwSqr1WY
Fetching comments for video: Ut_asYq95Qs
Fetching comments for video: RJ1hC_fI4QE
Fetching comments for video: VPt4i33Z7qY
Fetching comments for video: TkzAOeubVv4
Fetching comments for video: JD3VbmgNH1c
Fetching comments for video: aX4c1Ki_vSU
Fetching comments for video: 3dS6ZYA5OHg
Fetching comments for video: fzoV_1MpIkY
Fetching comments for video: a_H4OHchhmM
Fetching comments for video: 1H-sg4h43DY
Fetching comments for video: qisK4Yag42o
Fetching comments for video: OKLmHXU3w5E
Fetching comments for video: yr8s8vS7ka0
Fetching comments for video: cIN1uE27yzM
Fetching comments for video: oKy0eWPxqZo
Fetching comments for video: wWLEQKDFvlU
Fetching comments for video: VgmkxnpWfQ8
Fetching comments for video: 6A73Jl-0pW0
Fetching comments for video: W90RJNAuBn8
Fetching comments for video: aWEWMBqcryI
Fetching comments for video: WxOZKMv3GTY
Fetching comments for video: 3qBjKWZ0QN0
Fetching comments for video: E6RCgCOAY3s
Fetching comments for video: ODH4slNqPcc
Fetching comments for video: nuQKh-TXIFg
Fetching comments for video: cQyADXLRo3M
Fetching comments for video: goCKFp45Bu4
Fetching comments for video: ipZDBo1MDDc
Fetching comments for video: s_6TGMFfAl8
Fetching comments for video: IBFZHQSP9dc
Fetching comments for video: D1MhuoKSZ58
Fetching comments for video: 1yAQA-h6Ft0
Fetching comments for video: 3DLskeWHfCY
Fetching comments for video: feMTtusUkuI
Fetching comments for video: BQ4pBwwILYc
Fetching comments for video: rzGB4qkFLtg
Fetching comments for video: AO-mSQe9A_w
Fetching comments for video: W_xbo2SXSpU
Fetching comments for video: rXcJZAdcvjw
Fetching comments for video: WW91sPn5YjA
Fetching comments for video: 56w-jLFeXJQ
Fetching comments for video: d0VKIcPPLz0
Fetching comments for video: cQb6uJT6FqM
Fetching comments for video: npOYPXeRDk0
Fetching comments for video: rE2eE-Ht6Pc
Fetching comments for video: 5tSNoBy9MrU
Fetching comments for video: tZwK_KZXQzQ
Fetching comments for video: 7NFnOZlUEMI
Fetching comments for video: _J83Lt6jyUc
Fetching comments for video: mF9RKFH24Kg
Fetching comments for video: HV9je5fveDk
Fetching comments for video: rYpE_XQuGHQ
Fetching comments for video: MNapdYMqK7c

In [ ]:
# Information retrieved
comments_all.columns

Index(['video_id', 'comment_id', 'author', 'comment', 'likes', 'published_at',
       'channel'],
      dtype='object')

Given the high number of comment observations and given the fact that replies will be used only for the network analysis, we will assume that the analysis will be carried out only on the last 15 days.

In [ ]:
# Videos in the last 15 days
one_month_ago = datetime.now(timezone.utc) - timedelta(days=15)
videos_last_month = all_videos[pd.to_datetime(all_videos['published_at']) >= one_month_ago]

print(f"Videos in the last 15 days: {len(videos_last_month)}")
print(videos_last_month['channel'].value_counts())

Video ultimo mese: 413
channel
BBC News               122
The Young Turks        114
CNN                    101
The Jimmy Dore Show     76
Name: count, dtype: int64

In [ ]:
# Select comments for those videos
comments_last_month = comments_all[
    comments_all['video_id'].isin(videos_last_month['video_id'])
]

print(f"Comments on videos in the last 15 days: {len(comments_last_month)}")
print(comments_last_month['channel'].value_counts())

Commenti su video ultimo mese: 71911
channel
The Young Turks        20317
BBC News               19995
CNN                    16908
The Jimmy Dore Show    14691
Name: count, dtype: int64

In [ ]:
comments_last_month

,video_id,comment_id,author,comment,likes,published_at,channel
0,JiUoqt4cMrU,Ugy_8l4e89Y4_R0cHcZ4AaABAg,@clive5788,The sniffed up grifter is illegitimate anyhoo,0.0,2026-01-22 20:54:04+00:00,BBC News
1,JiUoqt4cMrU,UgyoO-LrLTC_3foFPLB4AaABAg,@craigsmith6512,I think the situation on the front is not good...,0.0,2026-01-22 20:50:22+00:00,BBC News
2,JiUoqt4cMrU,UgxHbp2nxnaZzcC_1vJ4AaABAg,@MarkKerrigan-o2v,Millions of pounds given to this country,1.0,2026-01-22 20:50:11+00:00,BBC News
3,JiUoqt4cMrU,UgyOHGcFGVVkOLcaqLh4AaABAg,@johancruijff4117,A mean junky,1.0,2026-01-22 20:49:31+00:00,BBC News
4,JiUoqt4cMrU,Ugyi9bYFVUpVZWw4pRF4AaABAg,@jamesgreen1116,Nato created a monster which will eventually t...,0.0,2026-01-22 20:49:11+00:00,BBC News
...,...,...,...,...,...,...,...
392426,fdZDbie1KRI,UgyFi_UBJRClL4dr0ZB4AaABAg,@BigB932,The Not Jimmy Dore show,13.0,2026-01-08 01:10:32+00:00,The Jimmy Dore Show
392427,fdZDbie1KRI,Ugw3HgW0YxKoYr4X0Sl4AaABAg,@user-dd7pq2to3o,Kurt needs to be put out to pasture,4.0,2026-01-08 01:09:17+00:00,The Jimmy Dore Show
392428,fdZDbie1KRI,UgyAw_sMaqC4nzJ2Hz94AaABAg,@RollTide-ix2rb,I WATCH JIMMY EVERY EPISODE AND MR. DORE THIS ...,3.0,2026-01-08 01:07:56+00:00,The Jimmy Dore Show
392429,fdZDbie1KRI,UgyIoMH2sJPpBIc26bd4AaABAg,@daverdal1,Go Trump !!,4.0,2026-01-08 01:07:11+00:00,The Jimmy Dore Show
392430,fdZDbie1KRI,Ugw3ZS59lATcLvbRbn94AaABAg,@Iranwar,Next is Iran,6.0,2026-01-08 01:06:12+00:00,The Jimmy Dore Show

For the network analysis, user interactions were reconstructed using replies to a stratified sample of top-level comments. Specifically, for each channel, the most liked comments published in the last two weeks were selected, as these comments are more likely to attract replies and generate discussion.

In [ ]:
# Definition of the funztion for fetching replies (default max are 100 replies per comment)
def get_comment_replies(parent_comment_id, max_results=100):
    replies = []
    try:
        request = youtube.comments().list(
            part="snippet",
            parentId=parent_comment_id,
            maxResults=max_results,
            textFormat="plainText"
        )
        response = request.execute()
        for reply in response.get("items", []):
            r = reply["snippet"]
            replies.append({
                "parent_id": parent_comment_id,
                "reply_id": reply["id"],
                "author": r["authorDisplayName"],
                "reply_text": r["textDisplay"],
                "likes": r["likeCount"],
                "published_at": r["publishedAt"]
            })
    except Exception as e:
        print(f"Error fetching replies for {parent_comment_id}: {e}")
    return pd.DataFrame(replies)

In [ ]:
# Function for sampling and then fetching the replies;
def sample_and_fetch_replies(comments_df, sample_size_per_channel=2000):
    # Sampling op sample_size for each channel by n_likes
    sampled_comments = comments_df.groupby('channel').apply(
        lambda x: x.nlargest(sample_size_per_channel, 'likes')
    ).reset_index(drop=True)

    print(f"Sampled {len(sampled_comments)} commenti totali")
    print(sampled_comments['channel'].value_counts())

    # Fetch replies on sampled comments
    replies_all = pd.DataFrame()
    for idx, row in sampled_comments.iterrows():
        cid = row['comment_id']
        df = get_comment_replies(cid, max_results=20)
        if not df.empty:
            df['video_id'] = row['video_id']
            df['channel'] = row['channel']
            replies_all = pd.concat([replies_all, df], ignore_index=True)
        time.sleep(0.3)

        # Partial saving for potential API limits
        if len(replies_all) % 1000 == 0 and len(replies_all) > 0:
            replies_all.to_csv(f"/content/drive/MyDrive/ANNO2/PRIMO PERIODO 2/SOCIAL MEDIA/PROJECT/replies_partial_{len(replies_all)}.csv", index=False)
            print(f"Saved {len(replies_all)} replies so far")

    # Final save
    replies_all.to_csv("/content/drive/MyDrive/ANNO2/PRIMO PERIODO 2/SOCIAL MEDIA/PROJECT/replies_final.csv", index=False)
    print(f"Totale replies ottenute: {len(replies_all)}")

    return replies_all

# Fetching of replies
replies_df = sample_and_fetch_replies(comments_last_month, sample_size_per_channel=1500)

/tmp/ipython-input-1981426047.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_comments = comments_df.groupby('channel').apply(

Sampled 6000 commenti totali
channel
BBC News               1500
CNN                    1500
The Jimmy Dore Show    1500
The Young Turks        1500
Name: count, dtype: int64
Saved 4000 replies so far
Saved 4000 replies so far
Saved 6000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 8000 replies so far
Saved 9000 replies so far
Saved 9000 replies so far
Totale replies ottenute: 10446

In [ ]:
replies_df['channel'].value_counts()

channel
BBC News               4656
The Young Turks        2219
The Jimmy Dore Show    2191
CNN                    1380
Name: count, dtype: int64

To account for the different analytical goals of the project, two separate datasets were constructed. A content-level dataset was used for linguistic and sentiment analysis of videos and comments, while a second interaction-level dataset was created specifically for network analysis, focusing on reply-based user interactions.

In [ ]:
# Merging information from videos to comment (filtered by last 15 days)
interaction_partial= comments_last_month.merge(videos_last_month[['video_id','title','description','published_at']],
                                               on = 'video_id',
                                               how= 'left')

In [ ]:
# Renaming columns
interaction_partial = interaction_partial.rename(columns={'author': 'comment_author',
                                                          'comment': 'comment_text',
                                                          'likes': 'comment_likes',
                                                          'published_at_x': 'comment_timestamp',
                                                          'published_at_y': 'video_timestamp'})
interaction_partial.columns

Index(['video_id', 'comment_id', 'comment_author', 'comment_text',
       'comment_likes', 'comment_timestamp', 'channel', 'title', 'description',
       'video_timestamp'],
      dtype='object')

In [ ]:
# Merging information from comments+video towards reply dataframe
interaction_df = replies_df.merge(interaction_partial, left_on= 'parent_id', right_on= 'comment_id', how= 'left')
interaction_df.columns

Index(['parent_id', 'reply_id', 'reply_author', 'reply_text', 'reply_likes',
       'reply_timestamp', 'video_id', 'channel_id', 'comment_id',
       'comment_author', 'comment_text', 'comment_likes', 'comment_timestamp',
       'title', 'description', 'video_timestamp'],
      dtype='object')

In [ ]:
# Rename amiguous columns
interaction_df = interaction_df.rename(columns={'author': 'reply_author',
                                                'likes': 'reply_likes',
                                                'published_at': 'reply_timestamp',
                                                'video_id_x' : 'video_id',
                                                'channel_x': 'channel_id'})

# Select only relevant ones
interaction_df = interaction_df[['parent_id', 'reply_id', 'reply_author', 'reply_text', 'reply_likes',
       'reply_timestamp', 'video_id', 'channel_id', 'comment_id',
       'comment_author', 'comment_text', 'comment_likes', 'comment_timestamp', 'title', 'description', 'video_timestamp']]

In [ ]:
# Save
interaction_df.to_csv('/content/drive/MyDrive/ANNO2/PRIMO PERIODO 2/SOCIAL MEDIA/PROJECT/interaction_df.csv')

The second dataframe is the one that will be used during the 'content' analysis. It merges information on all the videos and all the comments across the 4 months time horizon.

In [ ]:
# Merged videos to comments: final df will contain only video with at least one comment
content_df = comments_all.merge(all_videos, on="video_id", how="left")

In [ ]:
# Sanity check
content_df.columns

Index(['video_id', 'comment_id', 'author', 'comment', 'likes',
       'published_at_x', 'channel_x', 'title', 'description', 'published_at_y',
       'channel_id', 'channel_y'],
      dtype='object')

In [ ]:
# Rename ambigous columns post merge
content_df= content_df.rename(columns={'author': 'comment_author',
                                   'comment': 'comment_text',
                                   'likes': 'comment_likes',
                                   'published_at_x':'comment_timestamp',
                                   'channel_x' : 'channel',
                                   'published_at_y':'video_timestamp'})

# Select only relevant columns
content_df= content_df[['channel','video_id', 'video_timestamp', 'title', 'description',
             'comment_id', 'comment_author', 'comment_text', 'comment_likes',
             'comment_timestamp']]

In [ ]:
content_df.to_csv("/content/drive/MyDrive/ANNO2/PRIMO PERIODO 2/SOCIAL MEDIA/PROJECT/content_df.csv", index=False)